### ISSUE TITLE
multiple lines label

### ISSUE THREAD

**Issue by irsalshabirin** [linger1216/labelview#17]
sometimes I want to use multiple lines to `setLabelText()` in my `LabelView`
but, I got this result , "Already Transferred", with black background color
![whatsapp image 2016-08-06 at 18 25 09](https://cloud.githubusercontent.com/assets/4993269/17456513/33732532-5c04-11e6-9031-c25d00f9beed.jpeg)

thanks 👍

**Comment by linger1216** [comment]
can you share some code to me? i'll check later.

**Comment by linger1216** [comment]
hi irsalshabirin:
i already fix the bug about draw text offset, but i can fixed your requirements, because the Label view rect can not contain ur texts, it's affected by 3 parameters(distance, text size)

now:
![](http://i1.piimg.com/567571/b4c51ba1faedbd15.png)

large distance eg: 140dp
![](http://i1.piimg.com/567571/a914718cdf2356a6.png)

small text size:
![](http://i1.piimg.com/567571/445c42adad057aa1.png)


you can try ...

**Comment by irsalshabirin** [comment]
nice code, 💯  💯  💯 
But I want to make TextView has 2 lines ? is it possible ?

**Comment by linger1216** [comment]
i'm sorry, this feature is not supported now, but i will consider this...
2 lines is ok. 3,4,5 ?

**Comment by irsalshabirin** [comment]
I don't know for more than 2 lines, but I still need for 2 lines 👍 
thanks before. this library very cool 💯
